[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dandy = { git = "https://github.com/ncfavier/dandy", branch = "parse-grammar" }
wasm-bindgen = "0.2.90"
